FROM php:7.4-apache

# Включить mod_rewrite для Laravel
RUN a2enmod rewrite

# Установить зависимости и PHP-расширения
RUN apt-get update && apt-get install -y \
    autoconf \
    gcc \
    make \
    && pecl install xdebug-3.1.6 \
    && docker-php-ext-enable xdebug

# Установить Xdebug
RUN pecl install xdebug-3.1.6 \
    && docker-php-ext-enable xdebug

# Копируем конфиг Apache
COPY apache-vhost.conf /etc/apache2/sites-available/000-default.conf

# Закомментировать глобальный DocumentRoot
RUN sed -i 's|DocumentRoot /var/www/html|#DocumentRoot /var/www/html|g' /etc/apache2/apache2.conf

WORKDIR /var/www/html
